### ISSUE TITLE
API's response changing and not providing additional information in the fullUrl link

### ISSUE THREAD

**Issue by jeanraymonddaher** [dloic/carebook-coding-challenge#1]
Hello Loic ! 

While attempting to do the challenge, I have noticed the following behaviour and wanted to make sure that you are aware of its presence. 

The API http://hapi.fhir.org/baseDstu3/Patient?_pretty=true keeps modifying the response provided. 
Yesterday night, it was providing access to the patient's names; however today there is only one patient with a name. 

Moreover, the full details of the patient's endpoint, aka http://hapi.fhir.org/baseDstu3/Patient/1521078 does not have any additional information on the patient. It is a copy paste of the entries provided in the main root response.

Since the API keeps changing, I would, for the sake of the project, focus on the architecture of my solution and just append "not available" when the names are not available. 

I will still make the call to gather "more information" for a patient even if there is nothing different in the fullUrl response. 

Thanks !

**Comment by dloic** [comment]
Hi @jeanraymonddaher !

Very good catch! In fact, this server is a for test purpose when developers want to integrate with FHIR specification. Objects can be added, updated or removed at any time. Some patients may not have names, and it's fine if your implementation deal with this and display something like "name: not available".

Because you have to implement the list with pagination, we'll be sure to fetch enough patients so some have the required data, and thus display will be correct for some of them.

You can continue with your assumptions :)
